CREATE TABLE "impact_categories" (
  "UUID" uuid PRIMARY KEY,
  "nom_francais" varchar,
  "nom_anglais" varchar,
  "nom_origine_ilcd" varchar,
  "unite_de_reference" varchar,
  "description" varchar,
  "annee_reference" int,
  "niveau_recommandation" varchar,
  "commentaire_general" text,
  "zone_geographique" varchar,
  "source_donnees" varchar,
  "reference_modele" varchar,
  "format_jeu_donnees" varchar,
  "origine_jeu_donnees" varchar,
  "version_dataset" varchar,
  "time_independent" varchar,
  "informations_categorie_impact" text,
  "informations_dataset" text,
  "methode_standard" text,
  "methode_utilisateur" text,
  "categorie_et_classe" text,
  "reference_quantitative" text,
  "temps" text,
  "jeu_valable_jusqua" date,
  "description_representative_temps" text,
  "restrictions" text,
  "modelisation_validation" text,
  "traitement_representativite" text,
  "validation" text,
  "type_examen" text,
  "champ_application" text,
  "methodes" text,
  "indicateurs_qualite" text,
  "informations_admin" text,
  "commissaire" text,
  "commanditaire" text,
  "generateur_donnees" text,
  "saisie_donnees" text,
  "publication_propriete" text
);

CREATE TABLE "procedes" (
  "UUID" uuid PRIMARY KEY,
  "information_procede" text,
  "information_dataset" text,
  "nom_flux" varchar,
  "nom_anglais" varchar,
  "version" varchar,
  "quantite_produit" float,
  "synonymes" text,
  "synonyms" text,
  "flux_reference" varchar,
  "quantite_reference" float,
  "unite" varchar,
  "categorie_niv_1" varchar,
  "categorie_niv_2" varchar,
  "categorie_niv_3" varchar,
  "categorie_niv_4" varchar,
  "categorization_level_1" varchar,
  "categorization_level_2" varchar,
  "categorization_level_3" varchar,
  "categorization_level_4" varchar,
  "commentaire_general" text,
  "reference_quantitative" text,
  "temps" varchar,
  "annee_reference" int,
  "jeu_valable_jusqua" varchar,
  "description_representative_temps" text,
  "geographie" varchar,
  "zone_geographique" varchar,
  "technologie" varchar,
  "description_technologie" text,
  "objectif_technique" text,
  "diagramme_flux" varchar,
  "modelisation_validation" text,
  "methode_et_allocation_lci" text,
  "type_dataset" varchar,
  "principe_methode_lci" varchar,
  "deviations" text,
  "approche_lci" varchar,
  "deviations_b" text,
  "traitement_representativite" text,
  "donnees_coupure_principes" text,
  "selection_donnees_combinaison" text,
  "deviation_selection_combinaison" text,
  "traitement_donnees_extrapolations" text,
  "deviation_traitement_donnees" text,
  "source_donnees" varchar,
  "procedure_echantillonnage" varchar,
  "periode_collecte" varchar,
  "conseils_utilisation" text,
  "completude" varchar,
  "integralite_modele" text,
  "validation" text,
  "type_examen" text,
  "champ_application" text,
  "methodes" text,
  "indicateurs_qualite" text,
  "details_examen" text,
  "auteurs_et_institution" text,
  "autres_details_examen" text,
  "rapport_examen" text,
  "informations_admin" text,
  "commissaire" text,
  "commanditaire" varchar,
  "programme" text,
  "generateur_donnees" text,
  "reference_entite" text,
  "saisie_donnees_par" text,
  "reference_entree" text,
  "publication_propriete" text,
  "date_revision" date,
  "autorite_enregistrement" text,
  "numero_enregistrement" text,
  "proprietaire_dataset" text,
  "copyright" boolean,
  "droits_acces" text,
  "informations_extension" text,
  "confidentialite" varchar,
  "date_limite_confidentialite" varchar,
  "changement_affectation_sols" text,
  "methode" text,
  "parametres_methode" text,
  "identification_source_methode" text,
  "exclusions_non_respectees" text,
  "transports_consommateurs" text,
  "prise_en_compte_infrastructures" text,
  "frontieres_systeme" text,
  "uri" varchar,
  "respect_regles_coupure" text,
  "regles_allocation" text,
  "donnees_mix_electriques" text,
  "quantite_electricite" varchar,
  "product_allocation_value" varchar,
  "product_allocation_type" varchar,
  "product_allocation_comment" text,
  "donnees_mix_electriques_1" text,
  "mix_electrique_zone" text,
  "methodes_b" text,
  "ratio_nucleaire" float,
  "ratio_charbon" float,
  "ratio_gaz_naturel" float,
  "ratio_petrolier" float,
  "ratio_hydroelectrique" float,
  "ratio_eolien" float,
  "ratio_biomasse" float,
  "ratio_dechets" float,
  "ratio_solaire_photovoltaique" float,
  "ratio_solaire_thermique" float,
  "ratio_geothermie" float,
  "ratio_maremotrice" float,
  "ratio_autres" float,
  "commentaires_autres" text,
  "pertes_reseau" text,
  "valeur_pertes" varchar,
  "commentaires_mix" text,
  "pouvoir_calorifique_inferieur" varchar,
  "taux_degradation" varchar,
  "masse_flux_reference" varchar
);

CREATE TABLE "procedes_impacts" (
  "UUID_procede" UUID,
  "UUID_impact" UUID,
  "valeur" float
);


-- Clés et indexes -------------------------------------------------

-- Clé étrangère sur UUID_procede 
ALTER TABLE "procedes_impacts" ADD FOREIGN KEY ("UUID_procede") REFERENCES "procedes" ("UUID");

-- Clé étrangère sur UUID_impact
ALTER TABLE "procedes_impacts" ADD FOREIGN KEY ("UUID_impact") REFERENCES "impact_categories" ("UUID");

-- Clé primaire composite sur procedes_impacts
ALTER TABLE procedes_impacts
ADD CONSTRAINT procedes_impacts_pkey PRIMARY KEY ("UUID_procede", "UUID_impact");

-- Index sur UUID_impact (pour accélérer les jointures ou filtres sur cette colonne seule)
CREATE INDEX idx_procedes_impacts_uuid_impact
ON procedes_impacts("UUID_impact");